var maleNames*: seq[string] = @[
    "Alexander", "Alex", "Benjamin", "Ben", "Christopher", "Chris", "Dominic", "Dom",
    "Elliot", "Eli", "Frederick", "Fred", "Gabriel", "Gabe", "Harrison", "Harry",
    "Isaac", "Ike", "Jonathan", "Jon", "Kenneth", "Ken", "Leonardo", "Leo",
    "Matthew", "Matt", "Nathaniel", "Nate", "Oliver", "Ollie", "Patrick", "Pat",
    "Quentin", "Quinn", "Raphael", "Rafe", "Samuel", "Sam", "Theodore", "Theo",
    "Ulysses", "Victor", "William", "Will", "Liam", "Xavier", "Zachary", "Zach",
    "Adrian", "Aidan", "Arthur", "Asher", "Brandon", "Bryan", "Caleb", "Cameron",
    "Daniel", "Dan", "Dylan", "Ethan", "Finn", "Francis", "George", "Gideon",
    "Henry", "Ian", "Jack", "Jacob", "Jason", "Jasper", "Julian", "Kai",
    "Louis", "Lucas", "Marcus", "Mark", "Max", "Miles", "Nathan", "Nicholas",
    "Noah", "Owen", "Peter", "Philip", "Reuben", "Ryan", "Sebastian", "Simon",
    "Thomas", "Vincent", "Xander", "Zane", "Aaron", "Alan", "Albert", "Alfred",
    "Allen", "Amos", "Anthony", "Ashton", "Basil", "Blake", "Brian", "Byron",
    "Casey", "Cedric", "Charles", "Cliff", "Colin", "Corey", "Curtis", "Dean",
    "Dennis", "Derek", "Douglas", "Edgar", "Edward", "Edwin", "Elijah", "Emmett",
    "Erik", "Evan", "Fabian", "Felix", "Freddy", "Gabriel", "Gareth", "Gavin",
    "Grayson", "Hector", "Howard", "Hudson", "Hugh", "Ian", "Ignatius", "Isaias",
    "Ivan", "Jared", "Jeremiah", "Joel", "Jonah", "Jordan", "Julio", "Justin",
    "Keith", "Kelvin", "Kendrick", "Kyle", "Lance", "Lawrence", "Leon", "Leonel",
    "Logan", "Louis", "Malcolm", "Marcus", "Mario", "Martin", "Mason", "Micah",
    "Miguel", "Nathan", "Nelson", "Nicholas", "Noel", "Oliver", "Oscar", "Owen",
    "Patrick", "Paul", "Peter", "Philip", "Quentin", "Ralph", "Raymond", "Reid",
    "Richard", "Robert", "Rodney", "Roger", "Ronald", "Russell", "Ryan", "Samuel",
    "Scott", "Sean", "Sebastian", "Spencer", "Stephen", "Steven", "Terrence",
    "Thomas", "Timothy", "Trevor", "Tristan", "Victor", "Vincent", "Warren",
    "William", "Zachary", "Zane"
]

var femaleNames*: seq[string] = @[
    "Abigail", "Abby", "Beatrice", "Bea", "Charlotte", "Charlie", "Daniella", "Dani",
    "Eleanor", "Ellie", "Felicity", "Fay", "Gabrielle", "Gabby", "Hannah", "Hanna",
    "Isabella", "Bella", "Josephine", "Josie", "Katherine", "Kate", "Lillian", "Lily",
    "Madeline", "Maddie", "Natalie", "Nat", "Olivia", "Liv", "Penelope", "Penny",
    "Quinn", "Rachel", "Rebecca", "Becky", "Sophia", "Sophie", "Tabitha", "Tara",
    "Ursula", "Valerie", "Winifred", "Winnie", "Ximena", "Yvonne", "Zoey", "Zoe",
    "Alice", "Amelia", "Anna", "Annie", "Audrey", "Ava", "Bella", "Brianna",
    "Cecilia", "Clara", "Daphne", "Ella", "Emily", "Emma", "Fiona", "Grace",
    "Holly", "Iris", "Jane", "Julia", "Laura", "Leah", "Lucy", "Maya", "Megan",
    "Nora", "Paige", "Rose", "Ruby", "Sarah", "Stella", "Vera", "Victoria",
    "Vivian", "Willow", "Willa", "Abby", "Allison", "Angela", "Annie", "Bianca",
    "Brittany", "Camille", "Candice", "Carla", "Carmen", "Cassandra", "Celeste",
    "Cynthia", "Daisy", "Danielle", "Deborah", "Diana", "Eden", "Edith", "Elaine",
    "Eliza", "Ella", "Elsa", "Emilia", "Emma", "Erica", "Esther", "Eva", "Faith",
    "Faye", "Felicia", "Gabriella", "Gina", "Grace", "Hanna", "Harper", "Hazel",
    "Heather", "Helen", "Holly", "Isla", "Ivy", "Jacqueline", "Jade", "Jamie",
    "Jane", "Jasmine", "Jessica", "Joanna", "Joy", "Julia", "Juliana", "Kara",
    "Karen", "Katherine", "Katrina", "Kayla", "Leah", "Lena", "Lila", "Lillian",
    "Lily", "Linda", "Lisa", "Louise", "Lucia", "Lucy", "Lydia", "Macy", "Madeline",
    "Madison", "Maya", "Melanie", "Melissa", "Mia", "Michelle", "Molly", "Monica",
    "Nadia", "Natalie", "Nina", "Olivia", "Paige", "Patricia", "Rachel", "Rebecca",
    "Renee", "Rose", "Sabrina", "Samantha", "Sara", "Sarah", "Savannah", "Selena",
    "Sophie", "Stella", "Tara", "Taylor", "Vanessa", "Veronica", "Victoria",
    "Violet", "Vivian", "Wendy", "Whitney", "Yvonne", "Zoe"
]