CREATE UNIQUE INDEX IF NOT EXISTS idx_ai_key ON ai(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ammo_key ON ammo(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_biome_key ON biome(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_block_key ON block(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_buff_key ON buff(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_cook_key ON cook(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_craft_table_key ON craft_table(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_dungeon_key ON dungeon(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_enchant_key ON enchant(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_event_key ON event(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_fish_key ON fish(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_interactable_key ON interactable(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_interactable_pool_key ON interactable_pool(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_island_key ON island(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_item_key ON item(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_item_pool_key ON item_pool(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_loot_key ON loot(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mapchart_key ON mapchart(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mapgen_key ON mapgen(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mob_key ON mob(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mob_pool_key ON mob_pool(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_mount_key ON mount(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_npc_key ON npc(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_quest_key ON quest(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_recipe_key ON recipe(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_roof_key ON roof(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_script_key ON script(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sound_key ON sound(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_structure_key ON structure(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_summon_key ON summon(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tile_key ON tile(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_top_key ON top(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_top_pool_key ON top_pool(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_weather_key ON weather(Key);
CREATE UNIQUE INDEX IF NOT EXISTS idx_worldgen_key ON worldgen(Key);

CREATE UNIQUE INDEX IF NOT EXISTS idx_blacklist_category_id ON blacklist(category, id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_translations_key_lang ON translations(key, lang COLLATE NOCASE);